### DISCUSSION TITLE
Allow `environment` key within workflow steps

### DISCUSSION THREAD

**Discussion by chris3ware** [terrateamio/terrateam#425] [Ideas]
Currently I have an OIDC role with Read Only access that can be assumed from any branch. i.e. within a PR. I also have an OIDC role with CRUD access that only be assumed from the main branch. i.e. after a merge.

```
workflows:
  - tag_query: ""
    plan:
      - type: oidc
        provider: aws
        role_arn: arn:aws:iam::##########:role/github-oidc-plan
        session_name: terrateam-plan
      - type: init
      - type: plan
    apply:
      - type: oidc
        provider: aws
        role_arn: arn:aws:iam::##########:role/github-oidc-apply
        session_name: terrateam-apply
      - type: init
      - type: apply
```

This works well: access to the apply role is restricted by the trust policy only allowing the main branch - which is protected. 

If I add the `environment` key at the top level, the `sub` field changes. This is documented here: 

https://docs.github.com/en/actions/security-for-github-actions/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services#configuring-the-role-and-trust-policy

> If you use a workflow with an environment, the sub field must reference the environment name: repo:ORG-NAME/REPO-NAME:environment:ENVIRONMENT-NAME

This means that the _plan_ role and the _apply_ role can **both** be assumed within the pull request: effectively bypassing the pull request process. There is good blog outlining this here:

https://www.mechanicalrock.io/blog/bypassing-github-branch-protection-with-environments

If it was possible to add the `environment` key within a workflow step; then _apply_  and _plan_ could retain different trust policies -  with the added benefit of environment protection rules for applies.
