### ISSUE TITLE
Run terraform init in serial and use a cache dir

### ISSUE THREAD

**Issue by bender2352** [terrateamio/terrateam#170]
### Describe the feature

When running many `terraform init` commands, it's possible to run out of disk space in the github actions runtime environment. Run the `terraform init` in an `flock` and also set the `TF_PLUGIN_CACHE_DIR` environment variable.

For example:

```yaml
parallel_runs: 6
hooks:
  all:
    pre:
      - type: env
        name: TF_PLUGIN_CACHE_DIR
        cmd: ['echo', '/tmp']
workflows:
  - tag_query: ""
    terragrunt: true
    plan:
      - type: run
        cmd: ["flock", "--verbose", "/tmp/terraform-init.lock", "--command", "terragrunt init"]
      - type: plan
```
