### ISSUE TITLE
Access Control template is incorrectly rendered

### ISSUE THREAD

**Issue by schonfinkel** [terrateamio/terrateam#550]
### Describe the bug

We have a small issue in one of our templates that makes it get improperly rendered in some GitHub comments.

### Steps to reproduce

1. Given the following configuration:
```
access_control:
  apply_require_all_dirspace_access: false
  enabled: true
  policies:
  - apply: []
    plan:
    - '*'
    tag_query: dir:tf2
  - apply:
    - '*'
    plan:
    - '*'
    tag_query: ''
engine:
  name: tofu
when_modified:
  autoplan: false
```
2. And a user who successfully runs a `terrateam plan`, but does have access to the `dirspace`
3. Run `terrateam apply`

### Expected behavior

The rendered template is supposed to look like:

![Image](https://github.com/user-attachments/assets/4ce1a60a-ae9e-4ab5-bb76-fc26de825e43)

### Actual behavior

The template gets improperly rendered:

![Image](https://github.com/user-attachments/assets/cbdec930-9059-4502-bb71-fd8dbd723963)
